### PR TITLE
rerender with auto

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by scopatz** [comment]
@ocefpaf - did you add the 3.6 support manually? Or was that done by the rerender?

**Comment by ocefpaf** [comment]
Just rerender. Let me know if that is working. I'm away from my laptop now
and can't check.

**Comment by scopatz** [comment]
Yeah, rerendering isn't working for me on the cyclus-feedstock with conda-smithy v1.7.  Is there a way to do a hard rerender that you know of?

**Comment by ocefpaf** [comment]
aha! sorry but I forgot to mention I am rerendering with my hacked version
of conda-smithy. You are probably missing some dependency or some  .condarc
issues.

I'll take a look at this tomorrow for you.

**Comment by ocefpaf** [comment]
btw, my hacked version does exactly a 'hard rerender' by using a custom
index and leaving the package resolution to conda. making it easier to find
the missing packages.

**Comment by scopatz** [comment]
Ahh OK. Thanks!

**Pull request merged**
